### PR TITLE
fix: always close cmd when launching the application

### PR DESCRIPTION
**Pull request by DacoTaco**
there is no stream that executes more than 1 command and its anoyying to have the cmd be left open

### CODE REVIEW

**Comment by exelix11** [comment]
This behavior is purpose, in case of errors it makes it easier to read the log, otherwise the window would immediately close.

**Comment by DacoTaco** [comment]
then i suggest to write to a log file instead (using serilog or custom code)

**Comment by DacoTaco** [comment]
on top of that, launching the client from the generated bat doesn't keep it open either so this is 2 different ways the application reacts to the same action..

**Comment by exelix11** [comment]
> on top of that, launching the client from the generated bat doesn't keep it open either so this is 2 different ways the application reacts to the same action..

Actually you're right, looking at the code /K is used only for multiple commands, maybe to workaround some odd issue ? Don't remember why but there may be a reason. Will do some tests and get back at you.

> then i suggest to write to a log file instead (using serilog or custom code)

I'm not paid do to proper software engineering lmao.

**Comment by exelix11** [comment]
Huh the change from everything /K to /K only for single processes happened in [d5deb3c4bb8d3 ](https://github.com/exelix11/SysDVR/commit/d5deb3c4bb8d3acd7d86a37d63489f2bbf51790d#diff-15aa9735cd1fcf5883b35efc7093eb3252d0059e4b6efeba2c89332f1e1ead4cL101) 2y ago and i don't remember why.

Regardless, it is still fairly common for people who can't apparently read the guide to post error screenshots on discord when asking for help, I prefer keeping it this way as it cuts to the chase skipping the initial "a cmd appears and closes quickly" message.
If anything, i should remove the /C flag.

If you don't want the terminal to be left open use the bat file, that was the intended purpose.

**Comment by DacoTaco** [comment]
intended purpose or not, imo its a silly design. its like saying i should keep the logging on screen in priiloader on the wii. 
no, instead i create a log file and tell them to send that.

but ok, your program, your rules

**Comment by exelix11** [comment]
I agree but since i'm essentially done feature-wise on this project, at least for now, most of my time spent on it is helping people who ask for help on discord. Having a screen where even clueless users can clearly see what's wrong reduces the remote debugging time on my end.

I think the GUI leaving the terminal open is a good compromise since all the users i target with this design will go trhough it while everyone who finds this behavior annoying can make a lnk or bat file to avoid it.
Are there better alternatives ? Tons, but imo not worth the dev time.

**Pull request closed without merging**
