### PR TITLE
Added corrected Simplified Chinese translation

### PR DESCRIPTION
**Pull request by shooterspps**
Translate and proofread the ClientGUI text in Simplified Chinese

### CODE REVIEW

**Comment by exelix11** [comment]
I think @sskyNS was already working on a simplified chinese translation, would you mind taking a look at this ?

**Comment by exelix11** [comment]
So yeah sskyNS had already provided the jsons since we were in contact for a while on discord, feel free to proofread the translation in d7905baf285e4b9b064cbe2bc6af5cea51dba2cd

**Comment by shooterspps** [comment]
> So yeah sskyNS had already provided the jsons since we were in contact for a while on discord, feel free to proofread the translation in [d7905ba](https://github.com/exelix11/SysDVR/commit/d7905baf285e4b9b064cbe2bc6af5cea51dba2cd)

I just want to remind, this person: sskyNS (Chinese ID: 三上烤鸭), in the recent DBI incident is impressive, so there are reasons to doubt the purpose of his Chinese text, of course, if the original author said that does not matter is not a big problem, just a reminder of the previous this person is very bad, after the translation of the software will be the title of the exclusive right to sell illegally!

我只是提醒一下, 此人: sskyNS (中文ID: 三上烤鸭), 在前不久的 DBI 的事件中令人印象深刻, 所以有理由怀疑他做中文文本的目的性, 当然如果原作者表示无所谓也没大问题, 只是提醒一下, 之前此人人品很坏, 翻译软件后会冠名独占权进行非法贩卖!

**Comment by shooterspps** [comment]
> > So yeah sskyNS had already provided the jsons since we were in contact for a while on discord, feel free to proofread the translation in [d7905ba](https://github.com/exelix11/SysDVR/commit/d7905baf285e4b9b064cbe2bc6af5cea51dba2cd)
> 
> I just want to remind, this person: sskyNS (Chinese ID: 三上烤鸭), in the recent DBI incident is impressive, so there are reasons to doubt the purpose of his Chinese text, of course, if the original author said that does not matter is not a big problem, just a reminder of the previous this person is very bad, after the translation of the software will be the title of the exclusive right to sell illegally!

In the Chinese gaming community, most of the comments from gamers about this guy are negative, very bad, and very offensive!

我只是提醒一下, 此人: sskyNS (中文ID: 三上烤鸭), 在前不久的 DBI 的事件中令人印象深刻, 所以有理由怀疑他做中文文本的目的性, 当然如果原作者表示无所谓也没大问题, 只是提醒一下, 之前此人人品很坏, 翻译软件后会冠名独占权进行非法贩卖!

在中文游戏圈里, 玩家们对此人的评价大多是负面的, 非常糟糕的, 并且非常反感的!

> [rashevskyv/dbi#308](https://github.com/rashevskyv/dbi/issues/308)

**Comment by exelix11** [comment]
I did not know about this, thanks for heads up.
I simply preferred their translation because they were first in sending it to me but at this point i do believe this might have to do with their agenda.

Chinese support will still be included since now it's done but i'll take some time to think about the next steps.

**Comment by exelix11** [comment]
To give everyone a fair treatment i confronted the person in question and after some thinking i decided that it is not my problem and I will not pick a side.
Having official chinese support in the end is better than not having it so i'm not going to call anyone out for contributing it.

About selling homebrew, while I condemn re-selling other people's work due to obvious ethical reasons, it is not illegal since this and most other projects are licensed under GPL2. I will, of course, offer no support for unofficial repacks and add necessary disclaimers about it.

Again, thanks for the heads up but as long as the translation is correct I don't see any reason to outright reject it, other native speakers are of course welcome to contribute corrections or updates in the future.

**Pull request closed without merging**
